### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Filan-glitch** [Filan-glitch/StudiConnect#20]
Package: https://pub.dev/packages/flutter_native_splash

Ansprechende Splash Screens

**Comment by janbellenberg** [comment]
Also unter Android kann man einfach ein Bild unter \android\app\src\main\res\mipmap-xxxhdpi legen, aktuell ist dort ein Logo

**Comment by Filan-glitch** [comment]
da liegt auch ein splash screen, aber der wird nicht genutzt. kannst du dir einfach mal das package angucken? die scheint eigentlich ganz nice zu sein, kann man gut konfigurieren und nimmt halt die arbeit ab, was auch die sachen bezüglich ios angeht.
