### ISSUE TITLE
Update LocationDisplay

### ISSUE THREAD

**Issue by Filan-glitch** [Filan-glitch/StudiConnect#36]
Aktuell nutz ich das geolocator package für die anzeige, aber ich hab auch gesehen, dass du in deinem location picker ein anderes package nutzt. 
Würde das gerne einheitlich machen.
Und dazu kommt, dass ich noch ein Fehler irgendwo in der Profile edit page habe, weshalb immer nur "Adresse wird geladen..." angezeigt wird.

**Comment by janbellenberg** [comment]
Das hatte ich schon gefixt

**Comment by Filan-glitch** [comment]
Ah okay, hatte das nur in meinem fixes bemerkt, aber ja hast recht, seit dem merge tritt das nicht mehr auf...
