### ISSUE TITLE
Google Anmeldung

### ISSUE THREAD

**Issue by Filan-glitch** [Filan-glitch/StudiConnect#38]
Die Anmeldung funktioniert nicht. Nachdem man sein Google Konto ausgewählt hat gibt es ein unendlichen Ladebildschirm

**Comment by janbellenberg** [comment]
Gibt es logs?

**Comment by Filan-glitch** [comment]
Habs gefixed... mein SHA1 hatte gefehlt, ich denke mal, du hast dein darein getan, deshalb hats bei mir dann nicht mehr funktioniert...
