### ISSUE TITLE
Die Suche funktioniert nicht.

### ISSUE THREAD

**Issue by Filan-glitch** [Filan-glitch/StudiConnect#39]
Egal was man sucht, man findet alle Gruppen.
![Screenshot_20240109_215205.jpg](https://github.com/Filan-glitch/StudiConnect/assets/69374237/335d4133-06c6-4191-aa2f-1ad5442c0404)

**Comment by Filan-glitch** [comment]
Ich korrigiere mich, die such ergebnisse resetten sich nicht... wenn die suche verändert wird bleiben alte Suchergebnisse bestehen

**Comment by janbellenberg** [comment]
Hab das Scoring im Backend angepasst
