### ISSUE TITLE
App "crashed" bei reopen

### ISSUE THREAD

**Issue by Filan-glitch** [Filan-glitch/StudiConnect#45]
Wenn man die App in den Hintergrund packt (ich vermute wichtig ist, während sie etwas läd), und dann über die Offene Apps Ansicht wieder in die App zurückgeht kommt es manchmal zu freezes und/oder blackscreens, die nur mit nem App neustart oder einem ganz oft schnell öffnen/schließen gefixed werden kann.

**Comment by janbellenberg** [comment]
konnte ich nicht reproduzieren

**Comment by Filan-glitch** [comment]
Bei mehrfachem Testing auf verschiedenen Geräten über mehrere Tage nicht mehr aufgetreten. Ich close das issue hiermit.
